!cloudgene.mapred.util.Settings
name: Cloudgene WFS
apps:
  - id: mtdna-low
    filename: applications/cloudgene-apps-docker/mtdna-server/mtdna-default.yaml
    permission: user
hadoopPath: /usr
hdfsWorkspace: cloudgene-workspace-hdfs
localWorkspace: cloudgene-workspace-local
mail:
   port:
   smtp:
   name:
   password:
   user:
maxRunningJobs: 10
maxRunningJobsPerUser: 1
notificationAfter: 7
retireAfter: 10
removeHdfsWorkspace: true
streaming: false
streamingJar: /usr/contrib/streaming/hadoop-streaming-2.6.0-cdh5.4.5.jar
