!cloudgene.mapred.util.Settings
name: UM Imputationserver
apps:
  - id: wordcount
    permission: user
    filename: apps/wordcount/wordcount-mr-step.yaml
hadoopPath: /usr
hdfsWorkspace: cloudgene-workspace
localWorkspace: cloudgene-workspace
mail:
   port:
   smtp:
   name:
   password:
   user:
maintenance: false
maxRunningJobs: 10
maxRunningJobsPerUser: 1
notificationAfter: 7
removeHdfsWorkspace: true
retireAfter: 10
streaming: false
streamingJar: /usr/contrib/streaming/hadoop-streaming-2.6.0-cdh5.4.5.jar
